version: "2"

services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5002:5000"
    depends_on:
      - db

  db:
    image: library/mysql:8.0
    ports:
      - "32002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
